spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/codetest
    username: root
    password: huang1919.com
mybatis:
  configuration:
    map-underscore-to-camel-case: true
